version: '3'
services:
  client:
    container_name: client
    build: 
      context: './client'
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - "3003:8080"

  server:
    container_name: server
    build:
      context: './server'
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
