version: '3'
services:
  client:
    container_name: clientDev
    build: 
      context: './client'
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    volumes:
      - './client:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - "3003:8080"

  server:
    container_name: serverDev
    build: 
      context: './server'
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development